var a = require('./a.js')
a()
const c = require('./c.js')
  c()
require.ensure([], () => {
  const b = require('./b.js')
  b()
  const c = require('./c.js')
  c()
  const c = require('./c.js')
  c()
})
require.ensure(['./s'], () => {
  const c = require('./c.js')
  c()
})
var e = require('./a.js')
e()
var f = require('./a.js')
f()